Add example for dummy route in airgap
k3s-io/docs pull request #138
Opened 2023-06-02 18:11 UTC by dereknola

Addresses https://github.com/k3s-io/k3s/issues/1144

2023-06-05 19:34 UTC, brandond approved these changes

2023-06-05 19:39 UTC, brandond requested changes

2023-06-05 19:39 UTC, brandond commented on docs/installation/airgap.md
> +- K3s requires a default route in order to auto-detect the node's primary IP, and for kube-proxy ClusterIP routing to function properly. Therefore, a default route must be configured on each node, ev
Make it a little more clear that the dummy interface and route is only necessary if they don't have an interface with a default route. Not all airgap environments lack a local network.
```suggestion
- If your nodes do not have an interface with a default route, a default route must be configured; even a black-hole route via a dummy interface will suffice. K3s requires a default route in order to auto-detect the node's primary IP, and for kube-proxy ClusterIP routing to function properly. To add a dummy route, do the following:
```

2023-06-05 21:37 UTC, brandond approved these changes

2023-06-06 16:21 UTC, briandowns approved these changes

2023-06-06 16:53 UTC, merged