Updated network policy documentation
k3s-io/docs pull request #140
Opened 2023-06-06 13:52 UTC by rbrtbnfgl

Added a note on Network policy documentations related to the kube-router iptables rules that needs to be cleaned when K3s stopped.
issue: https://github.com/k3s-io/k3s/issues/7244

2023-06-06 16:55 UTC, dereknola requested changes

2023-06-06 16:55 UTC, dereknola commented on docs/networking/networking.md
> +Network policy configurations are not cleaned when K3s is stopped to rightly clean the configured kube-router iptables rules use the `k3s-killall.sh` script.
```suggestion
Network policy configurations are not cleaned  up when K3s is stopped. To correctly remove the configured kube-router iptables rules use the `k3s-killall.sh` script.
```

2023-06-06 23:30 UTC, brandond requested changes

2023-06-08 21:15 UTC, brandond requested changes

2023-06-08 21:15 UTC, brandond commented on docs/networking/networking.md
> +Network policy configurations are not cleaned up when K3s configuration is changed to disable it. To correctly remove the configured kube-router iptables rules, use the `k3s-killall.sh` script or cle
```suggestion
Network policy iptables rules are not removed if the K3s configuration is changed to disable the network policy controller. To clean up the kube-router network policy rules after disabling the network policy controller, use the `k3s-killall.sh` script, or clean them using `iptables-save` and `iptables-restore`. These steps must be run manually on all nodes in the cluster.
```

2023-06-09 17:15 UTC, dereknola approved these changes

2023-06-12 20:49 UTC, brandond approved these changes

2023-06-14 10:58 UTC, merged