Added IPv6 on the advertise-address description
k3s-io/docs pull request #182
Opened 2023-09-29 13:45 UTC by rbrtbnfgl

Added IPv6 also on the `advertise-address` description because is a valid value in case IPv6 is the primary address for the service CIDR.

2023-09-29 17:14 UTC, brandond requested changes

2023-09-29 17:14 UTC, brandond commented on docs/cli/server.md
> +| `--advertise-address` value | node-external-ip/node-ip | IPv4/6 address that apiserver uses to advertise to members of the cluster (note that the primary service cluster IP range should be of the s
We use `IPv4/IPv6` for other flag descriptions, and a nit on the wording.
I think the note will also look better on a separate line
```suggestion
| `--advertise-address` value | node-external-ip/node-ip | IPv4/IPv6 address that apiserver advertises for its service endpoint<br>Note that the primary `service-cidr` IP range must be of the same address family as the advertised address |
```

2023-10-02 18:44 UTC, brandond approved these changes

2023-10-10 09:39 UTC, manuelbuil approved these changes

2023-10-10 09:40 UTC, merged