Improve wording of network requirements
k3s-io/docs pull request #215
Opened 2023-12-06 09:17 UTC by wvell

2023-12-06 23:43 UTC, brandond requested changes
nit - vxlan OR wg ports, not both.

2023-12-06 23:43 UTC, brandond commented on docs/installation/requirements.md
> +The nodes need to be able to reach other nodes over UDP port 8472 when using the Flannel VXLAN backend, and over UDP port 51820 (and 51821 if IPv6 is used) when using the Flannel WireGuard backend. T
```suggestion
The nodes need to be able to reach other nodes over UDP port 8472 when using the Flannel VXLAN backend, or over UDP port 51820 (and 51821 if IPv6 is used) when using the Flannel WireGuard backend. The node should not listen on any other port. K3s uses reverse tunneling such that the nodes make outbound connections to the server and all kubelet traffic runs through that tunnel. However, if you do not use Flannel and provide your own custom CNI, then the ports needed by Flannel are not needed by K3s.
```

2023-12-07 19:37 UTC, brandond approved these changes

2023-12-07 20:21 UTC, dereknola approved these changes

2023-12-09 01:17 UTC, merged