Update manual upgrade page with better order of operations
k3s-io/docs pull request #251
Opened 2024-03-14 18:57 UTC by dereknola

Addresses: https://github.com/k3s-io/docs/issues/178

Mentions that you have to stop the existing K3s service before running the installation script with a new version.

2024-03-14 19:10 UTC, brandond commented
> have to stop the existing K3s service before running the installation script with a new version

Do you though? I thought that the install script would restart the service for you if the config or version changed.

2024-03-14 19:21 UTC, dereknola commented
Ah I guess your right. My brain was just on autopilot when looking at the install script output:

```
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s

```

We weirdly don't have output that the old k3s service was stopped.

2024-03-14 19:25 UTC, brandond commented
It's because we just log that we start it when actually we restart it. Which is either a start or a stop/start depending on current state.
https://github.com/k3s-io/k3s/blob/master/install.sh#L1042-L1045

2024-03-14 19:41 UTC, brandond requested changes

2024-03-14 19:41 UTC, brandond commented on docs/upgrades/manual.md
> +3. Start the new k3s service
```suggestion
2. Update the systemd unit or openrc init script to reflect the args passed to the install script
3. Restart the k3s service
```

2024-03-15 17:12 UTC, brandond approved these changes

2024-03-20 16:07 UTC, vitorsavian approved these changes

2024-03-20 16:07 UTC, cwayne18 approved these changes

2024-03-20 16:10 UTC, merged