docs: update nvidia container toolkit section
k3s-io/docs pull request #252
Opened 2024-03-14 20:50 UTC by beholdenkey

The Nvidia container runtime has been replaced with the Nvidia container toolkit. So I updated that. I have some more steps that can be added to help users set up the Nvidia GPU Operator, as that is a challenge in itself. Other than that, I made some syntax improvements. Please let me know what you think.

2024-03-14 22:58 UTC, brandond commented on docs/advanced.md
> +K3s will automatically detect and configure the NVIDIA container toolkit if it is present when K3s starts.
This is not correct. We detect the runtime, not the toolkit. As per https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/index.html:
> The toolkit includes a container runtime [library](https://github.com/NVIDIA/libnvidia-container) and utilities to automatically configure containers to leverage NVIDIA GPUs.

The runtime is all that we detect, we don't actually care if you get it from the toolkit or install it standalone

2024-03-14 23:01 UTC, brandond requested changes
Thanks for the contribution! I have a few notes.

2024-03-14 23:01 UTC, brandond commented on docs/advanced.md
> +4. Confirm that the nvidia container runtime has been found by k3s:
there appear to be a bunch of unrelated changes to whitespace and the list numbering. These don't affect the actual rendered doc content. Can you trim your changes down to just the link change and package name?

2024-03-15 16:55 UTC, dereknola commented
@beholdenkey You will also need to sign your commits to comply with DCO

2024-05-14 16:43 UTC, closed without merging