Rework snapshot docs
k3s-io/docs pull request #349
Opened 2024-10-30 18:14 UTC by brandond

Rework docs, and add documentation for ETCDSnapshotFiles and S3 config secret

2024-10-30 20:01 UTC, dereknola requested changes

2024-10-30 20:37 UTC, brandond commented on docs/cli/etcd-snapshot.md
>  :::info Version Gate
replaced it with a little intro paragraph.

2024-10-30 20:56 UTC, vitorsavian approved these changes

2024-10-31 16:25 UTC, dereknola approved these changes

2024-10-31 16:27 UTC, merged