Add VPN info
k3s-io/docs pull request #35
Opened 2022-10-19 16:25 UTC by manuelbuil

Adds information about how to enable the revised VPN feature that we will support in the October release (and further)

Signed-off-by: Manuel Buil <mbuil@suse.com>

2022-10-19 18:50 UTC, brandond approved these changes

2022-10-24 19:14 UTC, brandond requested changes

2022-10-24 19:14 UTC, brandond commented on docs/installation/network-options.md
> +--node-external-ip $AgentExternalIP --flannel-external-ip
I made `--flannel-external-ip` a cluster-level option, same as flannel-backend.

```suggestion
--node-external-ip $AgentExternalIP
```

2022-10-25 16:24 UTC, dereknola requested changes

2022-10-25 16:24 UTC, dereknola commented on docs/installation/network-options.md
> +--node-external-ip $ServerExternalIP --flannel-backend wireguard-native --flannel-external-ip
```suggestion
--node-external-ip <SERVER_EXTERNAL_IP> --flannel-backend wireguard-native --flannel-external-ip
```
Follows our standard "insert variable here" format we have in the rest of the docs.

2022-10-25 18:36 UTC, dereknola approved these changes

2022-10-25 19:52 UTC, brandond approved these changes

2022-10-25 19:59 UTC, merged