Net lb
k3s-io/docs pull request #93
Opened 2023-02-16 17:18 UTC by dereknola

Supersede https://github.com/k3s-io/docs/pull/75 with DCO signed

2023-02-16 18:13 UTC, brandond requested changes

2023-02-16 18:13 UTC, brandond commented on docs/networking/networking.md
> +In order for ServiceLB to assign nodes to pools, nodes must have the following label:
We still need the prior language explaining that adding the `enablelb` annotation to any node disables it on any unlabeled nodes. We just need to add a bit about `lbpool` also requiring `enablelb` on any pooled nodes.

2023-02-16 22:48 UTC, brandond requested changes

2023-02-16 22:48 UTC, brandond commented on docs/networking/networking.md
> +In order for ServiceLB to assign nodes to pools, nodes must have the following label:
```suggestion
To exclude nodes from being used by ServiceLB, add the following label to the nodes that should host ServiceLB Pods. Nodes that remain unlabeled will not be used for ServiceLB.
```

2023-02-16 22:48 UTC, brandond commented on docs/networking/networking.md
> +To select a particular subset of nodes to host pods for a LoadBalancer, set matching label values on the Nodes and Service. For example:
```suggestion
To select a particular subset of nodes to host pods for a LoadBalancer, add the `svccontroller.k3s.cattle.io/enablelb` label to the desired nodes, and set matching label values on the Nodes and Services. For example:
```

2023-02-16 22:48 UTC, brandond commented on docs/networking/networking.md
>  2. Label Node C and Node D with `svccontroller.k3s.cattle.io/lbpool=pool2`
```suggestion
1. Label Node A and Node B with `svccontroller.k3s.cattle.io/lbpool=pool1` and `svccontroller.k3s.cattle.io/enablelb=true`
2. Label Node C and Node D with `svccontroller.k3s.cattle.io/lbpool=pool2` and `svccontroller.k3s.cattle.io/enablelb=true`
```

2023-02-17 17:06 UTC, dereknola commented
I reworded the first part. I didn't like that we start with "this is how to turn this off", so I used and admonition to highlight that separately.
![image](https://user-images.githubusercontent.com/11727736/219717818-20448422-d001-45cc-9942-b08cdd69b03b.png)

2023-02-17 17:49 UTC, brandond approved these changes

2023-02-23 17:31 UTC, merged